#train_config.yaml
hyperparams:

  # Model Admin
  comment: "MSG, BCE, 2 Layers"
  exp_group: "Multi-Scale Grouping, 5 Layers"
  exp_group_min: "Minimum Model" 
  model: "pointnet2_sem_seg_msg"
  min_model: "fragrec_min"
  tag:  "MinimumModel" #"Overtraining" #"Debugging" #MinimumModel

  # General Hyperparameters
  batch_size: 4
  epoch: 150
  learning_rate: 0.001
  optimizer: "Adam"
  decay_rate: 1e-4
  sample_rate: 1.0
  step_size: 10
  lr_decay: 0.7
  dropout: False #boolean indicating whether dropout layer is used
  dropout_prob: 0.5

  # Data preparation and structure parameters
  additional_rotation: False
  labelweight_function: "(Npi/ 2 * Npi)"
  block_size: 30.0
  npoint: 10240  #number of points per block
  # No. centroids to sample around
  ncentroids: [1024, #ncentroids[0]
               512,  #ncentroids[1]
               256,  #ncentroids[2]
               128,  #ncentroids[3]
               64]   #ncentroids[4]
  # Set Asbtraction MLP's
  #TODO: Think about adjusting MLP sizes to the in_channel sizes
  sa_mlps: [[[16, 32, 64], [32, 32, 64]],             #sa_mlps[0]
            [[128, 128, 128], [128, 128, 128]],       #sa_mlps[1]
            [[256, 256, 256], [256, 256, 256]],       #sa_mlps[2]
            [[512, 512, 512], [512, 512, 512]],       #sa_mlps[3]
            [[1024, 1024, 1024], [1024, 1024, 1024]]] #sa_mlps[4]
  # Feature Propagation MLP's
  fp_mlps: [[2048, 1024],     #fp_mlps[0]
            [512, 512],       #fp_mlps[1]
            [256, 256],       #fp_mlps[2]
            [256, 128],       #fp_mlps[3]
            [128, 128, 128]]  #fp_mlps[4]
  # MSG Radii to sample within around centroids
  radius: [[0.2, 0.4], #radius[0]
           [0.4, 0.6], #radius[1]
           [0.8, 1.0], #radius[2]
           [1.2, 1.4], #radius[3]
           [1.6, 2.0]] #radius[4]

  # FOR MINIMUM MODEL
  # No. centroids to sample around
  ncentroids_min: [2048,  #ncentroids[0]
                   512]   #ncentroids[1]
  sa_mlps_min:  [[[16, 32, 64], [32, 32, 64]],
                 [[128, 256, 256], [128, 256, 256]]]
  fp_mlps_min:  [[512, 256], 
                 [256, 128, 128]]
  radius_min: [[2, 3],
               [3, 5]]

  # No. of samples around each centroid for given radius
  samples_around_centroid: [32, 64]

  loss_function: "BCE-Loss" #CE-Loss, BCE-Loss, NLL-Loss