#train_config.yaml
hyperparams:
  comment: "10 epoch run on kap dalton data_labelled_int"
  exp_group: "rotation"
  model: "pointnet2_sem_seg"
  batch_size: 8
  epoch: 30
  learning_rate: 0.001
  optimizer: "Adam"
  decay_rate: 1e-4
  npoint: 4096
  block_size: 4.0
  sample_rate: 1.0
  step_size: 10
  lr_decay: 0.7