#train_config.yaml
hyperparams:
  comment: "6 SA- &  FP-Layers, halfing centroid sampling from 2048 to 64"
  exp_group: "Layer Amount"
  model: "pointnet2_sem_seg"
  # General Hyperparameters
  batch_size: 8
  epoch: 150
  learning_rate: 0.001
  optimizer: "Adam"
  decay_rate: 1e-4
  sample_rate: 1.0
  step_size: 10
  lr_decay: 0.7
  dropout: False #boolean indicating whether dropout layer is used NEW
  dropout_prob: 0.5

  # Data preparation and structure parameters
  additional_rotation: False
  labelweight_function: "(Npi/ Npi)"
  block_size: 4.0
  npoint: 8192 #number of points per block
  ncentroids: [2048, 1024, 512, 256, 128, 64, 32]
  sa_mlps: [[32, 32, 64], [64, 64, 128], [128, 128, 256], [256, 256, 512], [512, 512, 1024], [1024, 1024, 1024], [1024, 1024, 2048]]
  fp_mlps: [[2048, 1024], [1024, 1024], [512, 512], [512, 256], [256, 256], [256, 128], [128, 128, 128]]
  radius: [0.1, 0.2, 0.4, 0.8, 1.2, 1.6, 2.0]
  samples_around_centroid: 32
  loss_function: "CE-Loss" #CE-Loss, BCE-Loss, NLL-Loss