#train_config.yaml
hyperparams:
  comment: "4 SA- &  FP-Layers standard, with MSG and BCE, complete run"
  exp_group: "Multi-Scale Grouping"
  model: "pointnet2_sem_seg_msg"
  tag: "Debugging" #"Overtraining"
  # General Hyperparameters
  batch_size: 8
  epoch: 150
  learning_rate: 0.001
  optimizer: "Adam"
  decay_rate: 1e-4
  sample_rate: 1.0
  step_size: 10
  lr_decay: 0.7
  dropout: False #boolean indicating whether dropout layer is used
  dropout_prob: 0.5

  # Data preparation and structure parameters
  additional_rotation: False
  labelweight_function: "(Npi/ Npi)"
  block_size: 12.0
  npoint: 8192  #number of points per block
  ncentroids: [1024, 256, 64, 16]
  sa_mlps: [[[16, 16, 32], [32, 32, 64]], [[64, 64, 128], [64, 96, 128]], [[128, 196, 256], [128, 196, 256]], [[256, 256, 512], [256, 384, 512]]]
  fp_mlps: [[256, 256], [256, 256], [256, 128], [128, 128, 128]]
  radius: [[0.1, 0.2], [0.2, 0.4], [0.4, 0.8], [0.8, 1.6]]
  samples_around_centroid: [16, 32]
  loss_function: "BCE-Loss" #CE-Loss, BCE-Loss, NLL-Loss