#infer_config.yaml
hyperparams:

  # Hyperparmas for inference
  min_model: "fragrec_min"
  ncentroids_min: [1024,  
                   512,
                   256, 
                   128,]
  radius_min: [[1.0, 1.5],
               [1.5, 2.0], 
               [2.0, 2.5],
               [2.5, 3.0]]
  samples_around_centroid: [32, 64]
  sa_mlps_min:  [[[16, 32, 64], [32, 32, 64]],
                 [[128, 256, 256], [128, 256, 256]],
                 [[512, 512, 512], [512, 512, 512]],
                 [[1024, 1024, 1024], [1024, 1024, 1024]]]
  fp_mlps_min:  [[2048, 1024],
                 [1024, 512],
                 [512, 256], 
                 [256, 128, 128]]
  loss_function: "BCE-Loss" #CE-Loss, BCE-Loss, NLL-Loss
  learning_rate: 0.02
  decay_rate: 1e-4
  batch_size: 4
  npoint: 10240